context:
  name: pyfonts
  version: "1.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyfonts/pyfonts-${{ version }}.tar.gz
  sha256: c0528f334fdca273a977466eeb3e1a4316e1b25e8175189d2c39452094d5ee46

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.9.1
    - requests

tests:
  - python:
      imports:
        - pyfonts
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  repository: https://github.com/JosephBARBIERDARNAL/pyfonts
  summary: 'A simple (and reproducible) way to load fonts for matplotlib.'
  description: |
    A simple (and reproducible) way to load fonts for matplotlib.
  license: MIT
  license_file: LICENSE
  homepage: https://python-graph-gallery.com/pyfonts/

extra:
  recipe-maintainers:
    - claudiushaag
