context:
  name: pyfonts
  version: "1.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyfonts/pyfonts-${{ version }}.tar.gz
  sha256: 82d4a336d0c46c35b0499cdc7f1b185190dd60884a12b1a91ecd9dc2c55dc9e6

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - requests

tests:
  - python:
      imports:
        - pyfonts
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  repository: https://github.com/y-sunflower/pyfonts
  summary: 'A simple (and reproducible) way to load fonts for matplotlib.'
  description: |
    A simple (and reproducible) way to load fonts for matplotlib.
  license: MIT
  license_file: LICENSE
  homepage: https://python-graph-gallery.com/pyfonts/

extra:
  recipe-maintainers:
    - claudiushaag
